### ISSUE TITLE
docker-compose usage exits

### ISSUE THREAD

**Issue by walkero-gr** [instrumentisto/phpdoc-docker-image#1]
Tried to use this container with docker-compose, inside a yml file, but it keeps exiting as soon as it runs. Is there a way to keep it running?

Also, to access it's interface there is a need to add a port mapping? If yes, this should be done to it's 80 port?

Thank you in advance for your help.

**Comment by tyranron** [comment]
@walkero-gr this image is supposed to run as command line tool and is build on top of PHP CLI version. No long running or daemonizing is expected.

AFAIK, phpDoc itself does not provide anything for serving documentation. It's just a tool to generate documentation from source code. Output documentation can be even not in HTML format.

If you want to serve your documentation, you are supposed to serve it as regular HTML static site. So, first, generate it with phpDoc. And, then, serve generated static HTML files with some web-server (for example [Nginx docker image](https://hub.docker.com/_/nginx/)).

**Comment by walkero-gr** [comment]
you are totally right. Thank you for the time you spent to explain me this...
